# Generated by Django 4.2.2 on 2023-12-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_image'),
        ),
    ]
